DATA = [
"are-large",
"are-medium",
"are-small",
"block",
"box",
"breadcrumb",
"breadcrumb has-arrow-separator",
"breadcrumb has-bullet-separator",
"breadcrumb has-dot-separator",
"breadcrumb has-succeeds-separator",
"button",
"button is-black",
"button is-danger",
"button is-dark",
"button is-fullwidth",
"button is-info",
"button is-large",
"button is-light",
"button is-link",
"button is-loading",
"button is-medium",
"button is-normal",
"button is-primary",
"button is-rounded",
"button is-small",
"button is-static",
"button is-success",
"button is-text",
"button is-warning",
"button is-white",
"buttons",
"buttons has-addons",
"buttons is-centered",
"buttons is-right",
"card",
"card-content",
"card-footer",
"card-footer-item",
"card-header",
"card-header-icon",
"card-header-title",
"card-image",
"card-imageimg",
"checkbox",
"checkboxinput",
"column",
"columns",
"columns is-centered",
"columns is-gapless",
"columns is-mobile",
"columns is-multiline",
"columns is-variable",
"columns is-vcentered",
"container",
"content",
"control",
"control has-icons-left",
"control has-icons-right",
"control is-loading",
"css",
"delete",
"dropdown",
"dropdown-content",
"dropdown-divider",
"dropdown-item",
"dropdown-menu",
"fa",
"field",
"field has-addons",
"field has-addons has-addons-centered",
"field has-addons has-addons-fullwidth",
"field has-addons has-addons-right",
"field is-grouped",
"field is-grouped is-grouped-centered",
"field is-grouped is-grouped-multiline",
"field is-grouped is-grouped-right",
"field-body",
"field-label",
"file",
"file has-name",
"file has-name is-empty",
"file is-boxed",
"file is-boxed has-name",
"file is-centered",
"file is-fullwidth",
"file is-right",
"file-cta",
"file-icon",
"file-input",
"file-label",
"file-name",
"footer",
"has-addons",
"has-addons-centered",
"has-addons-fullwidth",
"has-addons-right",
"has-arrow-separator",
"has-background-black",
"has-background-black-bis",
"has-background-black-ter",
"has-background-danger",
"has-background-danger-dark",
"has-background-danger-light",
"has-background-dark",
"has-background-grey",
"has-background-grey-dark",
"has-background-grey-darker",
"has-background-grey-light",
"has-background-grey-lighter",
"has-background-info",
"has-background-info-dark",
"has-background-info-light",
"has-background-light",
"has-background-link",
"has-background-link-dark",
"has-background-link-light",
"has-background-primary",
"has-background-primary-dark",
"has-background-primary-light",
"has-background-success",
"has-background-success-dark",
"has-background-success-light",
"has-background-warning",
"has-background-warning-dark",
"has-background-warning-light",
"has-background-white",
"has-background-white-bis",
"has-background-white-ter",
"has-bullet-separator",
"has-dot-separator",
"has-dropdown",
"has-dropdown-up",
"has-fixed-size",
"has-icons-left",
"has-icons-right",
"has-name",
"has-navbar-fixed-bottom",
"has-navbar-fixed-bottom-desktop",
"has-navbar-fixed-bottom-touch",
"has-navbar-fixed-top",
"has-navbar-fixed-top-desktop",
"has-navbar-fixed-top-touch",
"has-ratio",
"has-shadow",
"has-spaced-navbar-fixed-bottom",
"has-spaced-navbar-fixed-top",
"has-succeeds-separator",
"has-text-black",
"has-text-black-bis",
"has-text-black-ter",
"has-text-centered",
"has-text-danger",
"has-text-danger-dark",
"has-text-danger-light",
"has-text-dark",
"has-text-grey",
"has-text-grey-dark",
"has-text-grey-darker",
"has-text-grey-light",
"has-text-grey-lighter",
"has-text-info",
"has-text-info-dark",
"has-text-info-light",
"has-text-justified",
"has-text-left",
"has-text-light",
"has-text-link",
"has-text-link-dark",
"has-text-link-light",
"has-text-primary",
"has-text-primary-dark",
"has-text-primary-light",
"has-text-right",
"has-text-success",
"has-text-success-dark",
"has-text-success-light",
"has-text-warning",
"has-text-warning-dark",
"has-text-warning-light",
"has-text-weight-bold",
"has-text-weight-light",
"has-text-weight-medium",
"has-text-weight-normal",
"has-text-weight-semibold",
"has-text-white",
"has-text-white-bis",
"has-text-white-ter",
"heading",
"help",
"hero",
"hero is-fullheight",
"hero is-fullheight-with-navbar",
"hero is-halfheight",
"hero is-small",
"hero-body",
"hero-buttons",
"hero-foot",
"hero-head",
"hero-video",
"hero-videovideo",
"icon",
"icon-text",
"image",
"image is-128x128",
"image is-16by9",
"image is-16x16",
"image is-1by1",
"image is-1by2",
"image is-1by3",
"image is-24x24",
"image is-2by1",
"image is-2by3",
"image is-32x32",
"image is-3by1",
"image is-3by2",
"image is-3by4",
"image is-3by5",
"image is-48x48",
"image is-4by3",
"image is-4by5",
"image is-5by3",
"image is-5by4",
"image is-64x64",
"image is-96x96",
"image is-9by16",
"image is-square",
"input",
"is-0",
"is-0-desktop",
"is-0-fullhd",
"is-0-mobile",
"is-0-tablet",
"is-0-touch",
"is-0-widescreen",
"is-1",
"is-1-desktop",
"is-1-fullhd",
"is-1-mobile",
"is-1-tablet",
"is-1-touch",
"is-1-widescreen",
"is-10",
"is-10-desktop",
"is-10-fullhd",
"is-10-mobile",
"is-10-tablet",
"is-10-touch",
"is-10-widescreen",
"is-11",
"is-11-desktop",
"is-11-fullhd",
"is-11-mobile",
"is-11-tablet",
"is-11-touch",
"is-11-widescreen",
"is-12",
"is-12-desktop",
"is-12-fullhd",
"is-12-mobile",
"is-12-tablet",
"is-12-touch",
"is-12-widescreen",
"is-128x128",
"is-16by9",
"is-16x16",
"is-1by1",
"is-1by2",
"is-1by3",
"is-2",
"is-2-desktop",
"is-2-fullhd",
"is-2-mobile",
"is-2-tablet",
"is-2-touch",
"is-2-widescreen",
"is-24x24",
"is-2by1",
"is-2by3",
"is-3",
"is-3-desktop",
"is-3-fullhd",
"is-3-mobile",
"is-3-tablet",
"is-3-touch",
"is-3-widescreen",
"is-32x32",
"is-3by1",
"is-3by2",
"is-3by4",
"is-3by5",
"is-4",
"is-4-desktop",
"is-4-fullhd",
"is-4-mobile",
"is-4-tablet",
"is-4-touch",
"is-4-widescreen",
"is-48x48",
"is-4by3",
"is-4by5",
"is-5",
"is-5-desktop",
"is-5-fullhd",
"is-5-mobile",
"is-5-tablet",
"is-5-touch",
"is-5-widescreen",
"is-5by3",
"is-5by4",
"is-6",
"is-6-desktop",
"is-6-fullhd",
"is-6-mobile",
"is-6-tablet",
"is-6-touch",
"is-6-widescreen",
"is-64x64",
"is-7",
"is-7-desktop",
"is-7-fullhd",
"is-7-mobile",
"is-7-tablet",
"is-7-touch",
"is-7-widescreen",
"is-8",
"is-8-desktop",
"is-8-fullhd",
"is-8-mobile",
"is-8-tablet",
"is-8-touch",
"is-8-widescreen",
"is-9",
"is-9-desktop",
"is-9-fullhd",
"is-9-mobile",
"is-9-tablet",
"is-9-touch",
"is-9-widescreen",
"is-96x96",
"is-9by16",
"is-active",
"is-align-content-baseline",
"is-align-content-center",
"is-align-content-end",
"is-align-content-flex-end",
"is-align-content-flex-start",
"is-align-content-space-around",
"is-align-content-space-between",
"is-align-content-space-evenly",
"is-align-content-start",
"is-align-content-stretch",
"is-align-items-baseline",
"is-align-items-center",
"is-align-items-end",
"is-align-items-flex-end",
"is-align-items-flex-start",
"is-align-items-self-end",
"is-align-items-self-start",
"is-align-items-start",
"is-align-items-stretch",
"is-align-self-auto",
"is-align-self-baseline",
"is-align-self-center",
"is-align-self-flex-end",
"is-align-self-flex-start",
"is-align-self-stretch",
"is-ancestor",
"is-black",
"is-block",
"is-bold",
"is-bordered",
"is-boxed",
"is-capitalized",
"is-center",
"is-centered",
"is-child",
"is-clearfix",
"is-clickable",
"is-clipped",
"is-current",
"is-danger",
"is-dark",
"is-delete",
"is-disabled",
"is-empty",
"is-expanded",
"is-family-code",
"is-family-monospace",
"is-family-primary",
"is-family-sans-serif",
"is-family-secondary",
"is-fixed-bottom",
"is-fixed-bottom-desktop",
"is-fixed-bottom-touch",
"is-fixed-top",
"is-fixed-top-desktop",
"is-fixed-top-touch",
"is-flex",
"is-flex-direction-column",
"is-flex-direction-column-reverse",
"is-flex-direction-row",
"is-flex-direction-row-reverse",
"is-flex-grow-0",
"is-flex-grow-1",
"is-flex-grow-2",
"is-flex-grow-3",
"is-flex-grow-4",
"is-flex-grow-5",
"is-flex-shrink-0",
"is-flex-shrink-1",
"is-flex-shrink-2",
"is-flex-shrink-3",
"is-flex-shrink-4",
"is-flex-shrink-5",
"is-flex-wrap-nowrap",
"is-flex-wrap-wrap",
"is-flex-wrap-wrap-reverse",
"is-flexible",
"is-fluid",
"is-focused",
"is-four-fifths",
"is-four-fifths-desktop",
"is-four-fifths-fullhd",
"is-four-fifths-mobile",
"is-four-fifths-tablet",
"is-four-fifths-touch",
"is-four-fifths-widescreen",
"is-full",
"is-full-desktop",
"is-full-fullhd",
"is-full-mobile",
"is-full-tablet",
"is-full-touch",
"is-full-widescreen",
"is-fullheight",
"is-fullheight-with-navbar",
"is-fullwidth",
"is-gapless",
"is-ghost",
"is-grouped",
"is-grouped-centered",
"is-grouped-multiline",
"is-grouped-right",
"is-half",
"is-half-desktop",
"is-half-fullhd",
"is-half-mobile",
"is-half-tablet",
"is-half-touch",
"is-half-widescreen",
"is-halfheight",
"is-hidden",
"is-hoverable",
"is-hoverable-within",
"is-hovered",
"is-info",
"is-inline",
"is-inline-block",
"is-inline-flex",
"is-inverted",
"is-invisible",
"is-italic",
"is-justify-content-center",
"is-justify-content-end",
"is-justify-content-flex-end",
"is-justify-content-flex-start",
"is-justify-content-left",
"is-justify-content-right",
"is-justify-content-space-around",
"is-justify-content-space-between",
"is-justify-content-space-evenly",
"is-justify-content-start",
"is-large",
"is-left",
"is-light",
"is-link",
"is-loading",
"is-lower-alpha",
"is-lower-roman",
"is-lowercase",
"is-marginless",
"is-medium",
"is-mobile",
"is-multiline",
"is-narrow",
"is-normal",
"is-offset-0",
"is-offset-0-desktop",
"is-offset-0-fullhd",
"is-offset-0-mobile",
"is-offset-0-tablet",
"is-offset-0-touch",
"is-offset-0-widescreen",
"is-offset-1",
"is-offset-1-desktop",
"is-offset-1-fullhd",
"is-offset-1-mobile",
"is-offset-1-tablet",
"is-offset-1-touch",
"is-offset-1-widescreen",
"is-offset-10",
"is-offset-10-desktop",
"is-offset-10-fullhd",
"is-offset-10-mobile",
"is-offset-10-tablet",
"is-offset-10-touch",
"is-offset-10-widescreen",
"is-offset-11",
"is-offset-11-desktop",
"is-offset-11-fullhd",
"is-offset-11-mobile",
"is-offset-11-tablet",
"is-offset-11-touch",
"is-offset-11-widescreen",
"is-offset-12",
"is-offset-12-desktop",
"is-offset-12-fullhd",
"is-offset-12-mobile",
"is-offset-12-tablet",
"is-offset-12-touch",
"is-offset-12-widescreen",
"is-offset-2",
"is-offset-2-desktop",
"is-offset-2-fullhd",
"is-offset-2-mobile",
"is-offset-2-tablet",
"is-offset-2-touch",
"is-offset-2-widescreen",
"is-offset-3",
"is-offset-3-desktop",
"is-offset-3-fullhd",
"is-offset-3-mobile",
"is-offset-3-tablet",
"is-offset-3-touch",
"is-offset-3-widescreen",
"is-offset-4",
"is-offset-4-desktop",
"is-offset-4-fullhd",
"is-offset-4-mobile",
"is-offset-4-tablet",
"is-offset-4-touch",
"is-offset-4-widescreen",
"is-offset-5",
"is-offset-5-desktop",
"is-offset-5-fullhd",
"is-offset-5-mobile",
"is-offset-5-tablet",
"is-offset-5-touch",
"is-offset-5-widescreen",
"is-offset-6",
"is-offset-6-desktop",
"is-offset-6-fullhd",
"is-offset-6-mobile",
"is-offset-6-tablet",
"is-offset-6-touch",
"is-offset-6-widescreen",
"is-offset-7",
"is-offset-7-desktop",
"is-offset-7-fullhd",
"is-offset-7-mobile",
"is-offset-7-tablet",
"is-offset-7-touch",
"is-offset-7-widescreen",
"is-offset-8",
"is-offset-8-desktop",
"is-offset-8-fullhd",
"is-offset-8-mobile",
"is-offset-8-tablet",
"is-offset-8-touch",
"is-offset-8-widescreen",
"is-offset-9",
"is-offset-9-desktop",
"is-offset-9-fullhd",
"is-offset-9-mobile",
"is-offset-9-tablet",
"is-offset-9-touch",
"is-offset-9-widescreen",
"is-offset-four-fifths",
"is-offset-four-fifths-desktop",
"is-offset-four-fifths-fullhd",
"is-offset-four-fifths-mobile",
"is-offset-four-fifths-tablet",
"is-offset-four-fifths-touch",
"is-offset-four-fifths-widescreen",
"is-offset-half",
"is-offset-half-desktop",
"is-offset-half-fullhd",
"is-offset-half-mobile",
"is-offset-half-tablet",
"is-offset-half-touch",
"is-offset-half-widescreen",
"is-offset-one-fifth",
"is-offset-one-fifth-desktop",
"is-offset-one-fifth-fullhd",
"is-offset-one-fifth-mobile",
"is-offset-one-fifth-tablet",
"is-offset-one-fifth-touch",
"is-offset-one-fifth-widescreen",
"is-offset-one-quarter",
"is-offset-one-quarter-desktop",
"is-offset-one-quarter-fullhd",
"is-offset-one-quarter-mobile",
"is-offset-one-quarter-tablet",
"is-offset-one-quarter-touch",
"is-offset-one-quarter-widescreen",
"is-offset-one-third",
"is-offset-one-third-desktop",
"is-offset-one-third-fullhd",
"is-offset-one-third-mobile",
"is-offset-one-third-tablet",
"is-offset-one-third-touch",
"is-offset-one-third-widescreen",
"is-offset-three-fifths",
"is-offset-three-fifths-desktop",
"is-offset-three-fifths-fullhd",
"is-offset-three-fifths-mobile",
"is-offset-three-fifths-tablet",
"is-offset-three-fifths-touch",
"is-offset-three-fifths-widescreen",
"is-offset-three-quarters",
"is-offset-three-quarters-desktop",
"is-offset-three-quarters-fullhd",
"is-offset-three-quarters-mobile",
"is-offset-three-quarters-tablet",
"is-offset-three-quarters-touch",
"is-offset-three-quarters-widescreen",
"is-offset-two-fifths",
"is-offset-two-fifths-desktop",
"is-offset-two-fifths-fullhd",
"is-offset-two-fifths-mobile",
"is-offset-two-fifths-tablet",
"is-offset-two-fifths-touch",
"is-offset-two-fifths-widescreen",
"is-offset-two-thirds",
"is-offset-two-thirds-desktop",
"is-offset-two-thirds-fullhd",
"is-offset-two-thirds-mobile",
"is-offset-two-thirds-tablet",
"is-offset-two-thirds-touch",
"is-offset-two-thirds-widescreen",
"is-one-fifth",
"is-one-fifth-desktop",
"is-one-fifth-fullhd",
"is-one-fifth-mobile",
"is-one-fifth-tablet",
"is-one-fifth-touch",
"is-one-fifth-widescreen",
"is-one-quarter",
"is-one-quarter-desktop",
"is-one-quarter-fullhd",
"is-one-quarter-mobile",
"is-one-quarter-tablet",
"is-one-quarter-touch",
"is-one-quarter-widescreen",
"is-one-third",
"is-one-third-desktop",
"is-one-third-fullhd",
"is-one-third-mobile",
"is-one-third-tablet",
"is-one-third-touch",
"is-one-third-widescreen",
"is-outlined",
"is-overlay",
"is-paddingless",
"is-parent",
"is-primary",
"is-pulled-left",
"is-pulled-right",
"is-radiusless",
"is-relative",
"is-responsive",
"is-right",
"is-rounded",
"is-selected",
"is-shadowless",
"is-size-1",
"is-size-2",
"is-size-2-desktop",
"is-size-2-fullhd",
"is-size-2-mobile",
"is-size-2-tablet",
"is-size-2-touch",
"is-size-2-widescreen",
"is-size-3",
"is-size-3-desktop",
"is-size-3-fullhd",
"is-size-3-mobile",
"is-size-3-tablet",
"is-size-3-touch",
"is-size-3-widescreen",
"is-size-4",
"is-size-4-desktop",
"is-size-4-fullhd",
"is-size-4-mobile",
"is-size-4-tablet",
"is-size-4-touch",
"is-size-4-widescreen",
"is-size-5",
"is-size-5-desktop",
"is-size-5-fullhd",
"is-size-5-mobile",
"is-size-5-tablet",
"is-size-5-touch",
"is-size-5-widescreen",
"is-size-6",
"is-size-6-desktop",
"is-size-6-fullhd",
"is-size-6-mobile",
"is-size-6-tablet",
"is-size-6-touch",
"is-size-6-widescreen",
"is-size-7",
"is-size-7-desktop",
"is-size-7-fullhd",
"is-size-7-mobile",
"is-size-7-tablet",
"is-size-7-touch",
"is-size-7-widescreen",
"is-small",
"is-spaced",
"is-square",
"is-sr-only",
"is-static",
"is-success",
"is-tab",
"is-text",
"is-three-fifths",
"is-three-fifths-desktop",
"is-three-fifths-fullhd",
"is-three-fifths-mobile",
"is-three-fifths-tablet",
"is-three-fifths-touch",
"is-three-fifths-widescreen",
"is-three-quarters",
"is-three-quarters-desktop",
"is-three-quarters-fullhd",
"is-three-quarters-mobile",
"is-three-quarters-tablet",
"is-three-quarters-touch",
"is-three-quarters-widescreen",
"is-toggle",
"is-toggle-rounded",
"is-transparent",
"is-two-fifths",
"is-two-fifths-desktop",
"is-two-fifths-fullhd",
"is-two-fifths-mobile",
"is-two-fifths-tablet",
"is-two-fifths-touch",
"is-two-fifths-widescreen",
"is-two-thirds",
"is-two-thirds-desktop",
"is-two-thirds-fullhd",
"is-two-thirds-mobile",
"is-two-thirds-tablet",
"is-two-thirds-touch",
"is-two-thirds-widescreen",
"is-underlined",
"is-unselectable",
"is-up",
"is-upper-alpha",
"is-upper-roman",
"is-uppercase",
"is-variable",
"is-vcentered",
"is-vertical",
"is-warning",
"is-white",
"is-wrapped",
"label",
"level",
"level-item",
"level-left",
"level-right",
"list",
"list-item",
"list-item is-active",
"loader",
"m-0",
"m-1",
"m-2",
"m-3",
"m-4",
"m-5",
"m-6",
"m-auto",
"mb-0",
"mb-1",
"mb-2",
"mb-3",
"mb-4",
"mb-5",
"mb-6",
"mb-auto",
"media",
"media-content",
"media-left",
"media-right",
"menu",
"menu-label",
"menu-list",
"message",
"message-body",
"message-header",
"messagestrong",
"ml-0",
"ml-1",
"ml-2",
"ml-3",
"ml-4",
"ml-5",
"ml-6",
"ml-auto",
"modal",
"modal is-active",
"modal-background",
"modal-card",
"modal-card-body",
"modal-card-foot",
"modal-card-head",
"modal-card-title",
"modal-close",
"modal-content",
"mr-0",
"mr-1",
"mr-2",
"mr-3",
"mr-4",
"mr-5",
"mr-6",
"mr-auto",
"mt-0",
"mt-1",
"mt-2",
"mt-3",
"mt-4",
"mt-5",
"mt-6",
"mt-auto",
"mx-0",
"mx-1",
"mx-2",
"mx-3",
"mx-4",
"mx-5",
"mx-6",
"mx-auto",
"my-0",
"my-1",
"my-2",
"my-3",
"my-4",
"my-5",
"my-6",
"my-auto",
"navbar",
"navbar has-shadow",
"navbar is-fixed-bottom",
"navbar is-fixed-top",
"navbar-brand",
"navbar-burger",
"navbar-content",
"navbar-divider",
"navbar-dropdown",
"navbar-end",
"navbar-item",
"navbar-item-within",
"navbar-link",
"navbar-link-within",
"navbar-menu",
"navbar-start",
"navbar-tabs",
"notification",
"number",
"p-0",
"p-1",
"p-2",
"p-3",
"p-4",
"p-5",
"p-6",
"p-auto",
"pagination",
"pagination-ellipsis",
"pagination-link",
"pagination-link is-current",
"pagination-list",
"pagination-next",
"pagination-previous",
"panel",
"panel-block",
"panel-blockinput",
"panel-heading",
"panel-icon",
"panel-list",
"panel-tabs",
"pb-0",
"pb-1",
"pb-2",
"pb-3",
"pb-4",
"pb-5",
"pb-6",
"pb-auto",
"pl-0",
"pl-1",
"pl-2",
"pl-3",
"pl-4",
"pl-5",
"pl-6",
"pl-auto",
"pr-0",
"pr-1",
"pr-2",
"pr-3",
"pr-4",
"pr-5",
"pr-6",
"pr-auto",
"progress",
"pt-0",
"pt-1",
"pt-2",
"pt-3",
"pt-4",
"pt-5",
"pt-6",
"pt-auto",
"px-0",
"px-1",
"px-2",
"px-3",
"px-4",
"px-5",
"px-6",
"px-auto",
"py-0",
"py-1",
"py-2",
"py-3",
"py-4",
"py-5",
"py-6",
"py-auto",
"radio",
"section",
"select",
"subtitle",
"subtitle is-1",
"subtitle is-2",
"subtitle is-3",
"subtitle is-4",
"subtitle is-5",
"subtitle is-6",
"table",
"table is-bordered",
"table is-fullwidth",
"table is-hoverable",
"table is-hoverable is-striped",
"table is-narrow",
"table is-striped",
"table-container",
"tabs",
"tabs is-boxed",
"tabs is-centered",
"tabs is-fullwidth",
"tabs is-large",
"tabs is-medium",
"tabs is-right",
"tabs is-small",
"tabs is-toggle",
"tabs is-toggle is-toggle-rounded",
"tag",
"tags",
"tags are-large",
"tags are-medium",
"tags has-addons",
"tags is-centered",
"tags is-right",
"textarea",
"textarea has-fixed-size",
"tile",
"tile is-ancestor",
"tile is-child",
"tile is-parent",
"tile is-vertical",
"title",
"title is-1",
"title is-2",
"title is-3",
"title is-4",
"title is-5",
"title is-6",
]
